### ISSUE TITLE
[feature] Add comment when adding a label

### ISSUE THREAD

**Issue by prince-chrismc** [prince-chrismc/label-merge-conflicts-action#13]
Just adding a label would not notify the OP of the issue. Perhaps this would be a useful feature?

https://github.com/Marr11317/ConflictAdviser/blob/92e034569bbae5c6e6ec72555eb0de79bb8d26f6/lib/queries.js#L118-L128

**Comment by pt-br** [comment]
I think it is very useful.

I've actually forked your action and added this myself this way:

```
export const addLabelToLabelable = async (
  octokit: InstanceType<typeof GitHub>,
  {
    labelId,
    labelableId
  }: {
    labelId: string
    labelableId: string
  }
) => {
  const query = `mutation ($label: String!, $pullRequest: String!) {
    addLabelsToLabelable(input: {labelIds: [$label], labelableId: $pullRequest}) {
      clientMutationId
    }
  }`
  const addComment = `mutation comment($id: ID!, $body: String!) {
      addComment(input: {subjectId: $id, body: $body}) {
        clientMutationId
      }
    }
  `

  await octokit.graphql(query, {label: labelId, pullRequest: labelableId})

  return octokit.graphql(addComment, {
    id: labelableId,
    body: ':warning: There is a conflict on this PR. If you are the author, please solve it.'
  })
}
```

**Comment by prince-chrismc** [comment]
Thanks a ton for the code sample! I absolutely would love to have this feature added but it's been dragging.
With this I might be able to make time 🤞

**Comment by prince-chrismc** [comment]
@pt-br I merged a PR with this feature, let me know if it meets your needs!

**Comment by pt-br** [comment]
Looks perfect, thanks!

**Comment by pt-br** [comment]
Also @prince-chrismc, if you take a look on my recent changes on the fork, I've added a new feature to also post messages through Slack webhooks directly (that was my main initial goal)

Feel free to incorporate it on the action as well, as I think it might be interesting for other people to use :) (sorry, I really don't have a free gap to push a PR myself)
