### ISSUE TITLE
Consider removing the "This message is automatically generated.." note from comments

### ISSUE THREAD

**Issue by tdonohue** [prince-chrismc/label-merge-conflicts-action#567]
First off, thanks for this useful GitHub action!

The only (small) piece of feedback I'd have is to consider removing (or providing a way to turn off) this message when you configure `conflict_comment`:

```
***
This message is automatically generated by prince-chrismc/label-merge-conflicts-action so don't hesitate to report issues/improvements there.
```
https://github.com/prince-chrismc/label-merge-conflicts-action/blob/main/src/label.ts#L48-L50

While I understand the desire to point people back to this action's codebase (and to give you credit where credit is due), I feel the comment is sent to the wrong audience.  Some novice developers/contributors may decide to click on the link in that message to ask questions about their merge conflict (or how to resolve the merge conflict they were notified about).  The "automatically generated" message seems designed to be read by the lead developer(s), but in reality it may be sent to lower level developers or first time contributors who may not understand it's context.

Overall, it's a very minor quibble, I know.  But, it stood out enough to me to create you an issue ticket.  Feel free to just close this ticket though if you disagree.  Thanks again!

**Comment by prince-chrismc** [comment]
Thank you very much 💟 

I think a good comprise is only adding it in the default message?

No one has made a mistake yet but I absolutely understand where this request comes from

**Comment by tdonohue** [comment]
Yes, I think that’d be a good compromise as well. Thanks again for this useful action! In the last week, we’ve enabled it on our DSpace/DSpace GitHub repo, and it’s working well.
________________________________
