### ISSUE TITLE
Question: Permissions

### ISSUE THREAD

**Issue by ddevsr** [prince-chrismc/label-merge-conflicts-action#769]
@prince-chrismc I already added permission

```bash
issues: write
pull-requests: write
```

Why sometime happens `Resource not accessible by integration`?

https://github.com/codeigniter4/CodeIgniter4/actions/runs/6167549712/job/16739374912?pr=7924

**Comment by prince-chrismc** [comment]
You need to use `pull_request_target` if you receive PRs from public forks :) Just permissions isn't enough with GitHubs security rules.

https://github.com/codeigniter4/CodeIgniter4/blob/7253a41a59b217510bb74f55642b20c941fcee8f/.github/workflows/label-conflict.yml#L3

I have inform https://github.com/prince-chrismc/label-merge-conflicts-action#faq---how-do-i-fix-resource-not-accessible-by-integration with links
